name: hammer_ops_server
description: Simple Dart backend for Hammer Ops (Shelf + Drift)
version: 0.1.0
publish_to: "none"

environment:
  sdk: ^3.9.0

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  drift: ^2.28.1
  drift_postgres: ^1.2.0
  postgres: ^3.0.5
  sqlite3: ^2.9.0
  sqlite3_flutter_libs: ^0.5.39
  path: ^1.9.0
  crypto: ^3.0.6
  jose: ^0.3.3
  hammer_ops:
    path: ..
  mailer: ^6.1.2

dev_dependencies:
  drift_dev: ^2.28.2
  build_runner: ^2.7.2
  lints: ^5.1.1
